### ISSUE TITLE
nvidia GT 710 crash during startup

### ISSUE THREAD

**Issue by mrgtwentythree** [riastradh/netbsd-src#37]
this worked for a different GT 710 card a month ago, in a Ryzen 3600.
this system is an Asrock A520M/ac board with a Ryzen 5600G.

[   1.0425900] nouveau0 at pci1 dev 0 function 0: NVIDIA GeForce GT 710 (rev. 0xa1)
[ .... ]
[  11.4248687] nouveau0: info: NVIDIA GK208B (b060b0b1)
[  11.4248687] clock: unknown CMOS layout
[  11.5348701] nouveau0: info: bios: version 80.28.a6.00.01
[  11.5471851] allocated pic msi11 type edge pin 0 level 6 to cpu1 slot 6 idt entry 100
[  11.5471851] nouveau0: interrupting at msi11 vec 0 (nouveau0)
[  11.5471851] nouveau0: info: fb: 1024 MiB DDR3
[  11.7548691] Zone  kernel: Available graphics memory: 11085668 KiB
[  11.7548691] Zone   dma32: Available graphics memory: 2097152 KiB
[  11.7548691] nouveau0: info: DRM: VRAM: 1024 MiB
[  11.7687985] nouveau0: info: DRM: GART: 1048576 MiB
[  11.7687985] nouveau0: info: DRM: TMDS table version 2.0
[  11.7767124] nouveau0: info: DRM: DCB version 4.0
[  11.7767124] nouveau0: info: DRM: DCB outp 00: 01000f02 00020030
[  11.7767124] nouveau0: info: DRM: DCB outp 01: 02011f62 00020010
[  11.7886903] nouveau0: info: DRM: DCB outp 02: 02022f10 00000000
[  11.7886903] nouveau0: info: DRM: DCB conn 00: 00001031
[  11.7967035] nouveau0: info: DRM: DCB conn 01: 00002161
[  11.7967035] nouveau0: info: DRM: DCB conn 02: 00000200
[  11.8048694] nouveau0: info: DRM: MM: using COPY for buffer copies
[  11.8048694] kern info: [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[  11.8048694] kern info: [drm] Driver supports precise vblank timestamp query.
[  11.8848698] nouveaufb0 at nouveau0
[  11.8848698] kern info: [drm] Initialized nouveau 1.3.1 20120801 for nouveau0 on minor 0
[  11.8960920] nouveaufb0: framebuffer at 0x7ff00c0000, size 1920x1200, depth 32, stride 7680
[  13.8948750] nouveau0: autoconfiguration error: error: DRM: base-0: timeout
[  13.9248769] wsdisplay0 at nouveaufb0 kbdmux 1: console (default, vt100 emulation), using wskbd0
[  13.9248769] wsmux1: connecting to wsdisplay0
[  13.9248769] nouveau0: autoconfiguration error: error: fifo: fault 01 [WRITE] at 0000000000940000 engine 04 [BAR1] client 08 [HUB/HOST_CPU_NB] reason 02 [PTE] on channel -1 [003fda7000 unknown]
[  13.9548752] iwm0: hw rev 0x220, fw ver 22.361476.0, address 90:cc:df:64:64:c8
[  26.8549091] wsdisplay0: screen 1 added (default, vt100 emulation)
[  26.8549091] wsdisplay0: screen 2 added (default, vt100 emulation)
[  26.8549091] wsdisplay0: screen 3 added (default, vt100 emulation)
[  26.8549091] wsdisplay0: screen 4 added (default, vt100 emulation)
[  69.0549350] nouveau0: autoconfiguration error: error: fifo: fault 01 [WRITE] at 000000000002f000 engine 15 [CE0] client 01 [HUB/CE0] reason 02 [PTE] on channel 1 [003fc45000 DRM]
[  69.0549350] nouveau0: notice: fifo: channel 1: killed
[  69.0549350] nouveau0: notice: fifo: runlist 4: scheduled for recovery
[  69.0549350] nouveau0: notice: fifo: engine 4: scheduled for recovery
[  69.0549350] nouveau0: warn: DRM: channel 1 killed!
[  69.0549350] panic: kernel diagnostic assertion "(atomic_load_relaxed(&fence->flags) & (1u << DMA_FENCE_FLAG_SIGNALED_BIT)) == 0" failed: file "/usr/branches/riastradh-drm/netbsd-src/sys/external/bsd/drm2/linux/linux_dma_fence.c", line 670
[  69.0549350] cpu1: Begin traceback...
[  69.0549350] vpanic() at netbsd:vpanic+0x156
[  69.0549350] __x86_indirect_thunk_rax() at netbsd:__x86_indirect_thunk_rax
[  69.0549350] linux_dma_fence_set_error() at netbsd:linux_dma_fence_set_error+0x176
[  69.0549350] nouveau_fence_context_kill() at netbsd:nouveau_fence_context_kill+0x4e
[  69.0549350] nouveau_channel_killed() at netbsd:nouveau_channel_killed+0x5c
[  69.0549350] nvif_notify_work() at netbsd:nvif_notify_work+0x2b
[  69.0549350] linux_workqueue_thread() at netbsd:linux_workqueue_thread+0x189
[  69.0549350] cpu1: End traceback...

i have a working core file:

(gdb) bt
#0  0xffffffff80226155 in cpu_reboot (howto=howto@entry=260, bootstr=bootstr@entry=0x0)
    at /usr/branches/riastradh-drm/netbsd-src/sys/arch/amd64/amd64/machdep.c:720
#1  0xffffffff80b78454 in kern_reboot (howto=howto@entry=260, bootstr=bootstr@entry=0x0) at /usr/branches/riastradh-drm/netbsd-src/sys/kern/kern_reboot.c:73
#2  0xffffffff80bbb112 in vpanic (fmt=0xffffffff80fee228 "kernel %sassertion \"%s\" failed: file \"%s\", line %d ", ap=ap@entry=0xffff89825c8c1e18)
    at /usr/branches/riastradh-drm/netbsd-src/sys/kern/subr_prf.c:290
#3  0xffffffff80d30eef in kern_assert (fmt=fmt@entry=0xffffffff80fee228 "kernel %sassertion \"%s\" failed: file \"%s\", line %d ")
    at /usr/branches/riastradh-drm/netbsd-src/sys/lib/libkern/kern_assert.c:51
#4  0xffffffff80ce8200 in linux_dma_fence_set_error (fence=fence@entry=0xfffff6238a37ae08, error=error@entry=-19)
    at /usr/branches/riastradh-drm/netbsd-src/sys/external/bsd/drm2/linux/linux_dma_fence.c:670
#5  0xffffffff80751a75 in nouveau_fence_context_kill (fctx=0xfffff6237eedf988, error=-19)
    at /usr/branches/riastradh-drm/netbsd-src/sys/external/bsd/drm2/dist/drm/nouveau/nouveau_fence.c:106
#6  0xffffffff8074a37c in nouveau_channel_killed (ntfy=0xfffff6237ef62c50)
    at /usr/branches/riastradh-drm/netbsd-src/sys/external/bsd/drm2/dist/drm/nouveau/nouveau_chan.c:64
#7  0xffffffff8075965b in nvif_notify_func (keep=true, notify=0xfffff6237ef62c50)
    at /usr/branches/riastradh-drm/netbsd-src/sys/external/bsd/drm2/dist/drm/nouveau/nvif/nouveau_nvif_notify.c:98
#8  nvif_notify_work (work=0xfffff6237ef62c90) at /usr/branches/riastradh-drm/netbsd-src/sys/external/bsd/drm2/dist/drm/nouveau/nvif/nouveau_nvif_notify.c:113
#9  0xffffffff809b3546 in linux_workqueue_thread (cookie=0xfffff62a7b80bc00)
    at /usr/branches/riastradh-drm/netbsd-src/sys/external/bsd/common/linux/linux_work.c:453
#10 0xffffffff8020b327 in lwp_trampoline ()

**Comment by mrgtwentythree** [comment]
when is say "start up", i mean, when i run X.

i had tested a GT 710 in July successfully, it never generates any of the
errors, these from the above:

[ 13.9248769] nouveau0: autoconfiguration error: error: fifo: fault 01 [WRITE] at 0000000000940000 engine 04 [BAR1] client 08 [HUB/HOST_CPU_NB] reason 02 [PTE] on channel -1 [003fda7000 unknown]
 [ 13.9248769] nouveau0: autoconfiguration error: error: fifo: fault 01 [WRITE] at 0000000000940000 engine 04 [BAR1] client 08 [HUB/HOST_CPU_NB] reason 02 [PTE] on channel -1 [003fda7000 unknown]
[ 69.0549350] nouveau0: notice: fifo: channel 1: killed
[ 69.0549350] nouveau0: notice: fifo: runlist 4: scheduled for recovery
[ 69.0549350] nouveau0: notice: fifo: engine 4: scheduled for recovery
[ 69.0549350] nouveau0: warn: DRM: channel 1 killed!
[ 69.0549350] panic: kernel diagnostic assertion [ .. crash as above .. ]

so the crash is in this error handling path i guess.
